### ISSUE TITLE
NPE when clicking outside the inventory screen with LoreLock items.

### ISSUE THREAD

**Issue by TfT-02** [derwisch/loreLocks#2]
```
13:11:12 [SEVERE] Could not pass event InventoryClickEvent to LoreLocks v1.0.1.1
org.bukkit.event.EventException
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:427)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
    at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:477)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:462)
    at net.minecraft.server.v1_4_R1.PlayerConnection.a(PlayerConnection.java:1186)
    at net.minecraft.server.v1_4_R1.Packet102WindowClick.handle(SourceFile:31)
    at net.minecraft.server.v1_4_R1.NetworkManager.b(NetworkManager.java:290)
    at net.minecraft.server.v1_4_R1.PlayerConnection.d(PlayerConnection.java:113)
    at net.minecraft.server.v1_4_R1.ServerConnection.b(SourceFile:39)
    at net.minecraft.server.v1_4_R1.DedicatedServerConnection.b(SourceFile:30)
    at net.minecraft.server.v1_4_R1.MinecraftServer.r(MinecraftServer.java:598)
    at net.minecraft.server.v1_4_R1.DedicatedServer.r(DedicatedServer.java:224)
    at net.minecraft.server.v1_4_R1.MinecraftServer.q(MinecraftServer.java:494)
    at net.minecraft.server.v1_4_R1.MinecraftServer.run(MinecraftServer.java:427)
    at net.minecraft.server.v1_4_R1.ThreadServerApplication.run(SourceFile:849)
Caused by: java.lang.NullPointerException
    at com.github.derwisch.loreLocks.LoreLocks.IsKey(LoreLocks.java:316)
    at com.github.derwisch.loreLocks.LoreLocksListener.onInventoryClick_ApplyKey(LoreLocksListener.java:109)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:425)
    ... 14 more
```

Using LoreLocks v1.0.1.1

**Comment by derwisch** [comment]
Fixed in current version, will be uploaded when I fixed another bug

**Comment by TfT-02** [comment]
Alright, great. :)
